// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJwqeokFJlWjDa_0pXH6puEtaoL4WN-Bs',
    appId: '1:451212028757:web:af63723f2e92dcf96f5ddc',
    messagingSenderId: '451212028757',
    projectId: 'young-7d242',
    authDomain: 'young-7d242.firebaseapp.com',
    storageBucket: 'young-7d242.appspot.com',
    measurementId: 'G-PW89WHQ5L4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ9JtdgsoI1wGqeLaP2SyHwv2wCq-KHBY',
    appId: '1:451212028757:android:edb317be511a603e6f5ddc',
    messagingSenderId: '451212028757',
    projectId: 'young-7d242',
    storageBucket: 'young-7d242.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo4-P9QmdpdMjStkXhNek-yLIx1_BfItE',
    appId: '1:451212028757:ios:7b1c13decf1c00196f5ddc',
    messagingSenderId: '451212028757',
    projectId: 'young-7d242',
    storageBucket: 'young-7d242.appspot.com',
    iosBundleId: 'com.example.young',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo4-P9QmdpdMjStkXhNek-yLIx1_BfItE',
    appId: '1:451212028757:ios:7b1c13decf1c00196f5ddc',
    messagingSenderId: '451212028757',
    projectId: 'young-7d242',
    storageBucket: 'young-7d242.appspot.com',
    iosBundleId: 'com.example.young',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJwqeokFJlWjDa_0pXH6puEtaoL4WN-Bs',
    appId: '1:451212028757:web:257a6d548df697e06f5ddc',
    messagingSenderId: '451212028757',
    projectId: 'young-7d242',
    authDomain: 'young-7d242.firebaseapp.com',
    storageBucket: 'young-7d242.appspot.com',
    measurementId: 'G-9FL1N01W9V',
  );

}
